In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import viz # curriculum example visualizations

np.random.seed(29)

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [3]:
#rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (100000, 2))
#rolls

#(rolls[:,0] == rolls[:,1]).mean()

#roll1 = np.random.choice([1,2,3,4,6,]), size = (100000,1)
#roll2 = np.random.choice([1,2,3,4,6,]), size = (100000,1)

#(roll1 ==roll2).mean()

In [4]:
rolls_df = pd.DataFrame(rolls, columns=['roll_1', 'roll_2'])
rolls_df.head()

roll_1  roll_2
0       6       4
1       5       6
2       3       1
3       1       2
4       2       1

In [5]:
rolls_df['doubles'] = rolls_df['roll_1'] == rolls_df['roll_2']

rolls_df['doubles'].head()

0    False
1    False
2    False
3    False
4    False
Name: doubles, dtype: bool

In [6]:
rolls_df['doubles'] = rolls_df['roll_1'] == rolls_df['roll_2']

rolls_df['doubles'].tail()

9995    False
9996    False
9997    False
9998    False
9999    False
Name: doubles, dtype: bool

In [7]:
rolls_df['doubles'].sum()

1709

In [8]:
rolls_df['doubles'].count()

10000

In [9]:
how_likely = rolls_df['doubles'].sum()/rolls_df['doubles'].count()

how_likely * 100

17.09

In [10]:
#flips = np.random.choice([0, 1], size = (1000000, 8))
#flips

#flips.sum(axis = 1)

In [11]:
n_trials = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0, 1], size = (n_trials, n_coins))
flips

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [12]:
flips_df = pd.DataFrame(flips, columns=['flip_1', 'flip_2', 'flip_3','flip_4','flip_5','flip_6','flip_7','flip_8'])
flips_df.head()

flip_1  flip_2  flip_3  flip_4  flip_5  flip_6  flip_7  flip_8
0       0       0       0       0       1       0       1       1
1       0       0       1       1       1       1       1       0
2       1       0       1       0       1       1       1       1
3       0       1       0       0       0       0       1       1
4       1       0       0       1       0       0       1       1

In [13]:
flips_df['row_total'] = flips_df.sum(axis = 1)

flips_df['row_total'].head()

0    3
1    5
2    6
3    3
4    4
Name: row_total, dtype: int64

In [14]:
sum(flips_df['row_total'] == 3)

2243

In [15]:
sum(flips_df['row_total'] == 3)/10000 * 100

22.43

In [16]:
sum(flips_df['row_total'] > 3)

6313

In [17]:
sum(flips_df['row_total'] > 3)/10000 * 100

63.129999999999995

In [18]:
#bb = np.random.choice([0,1], size = (10000, 2), p = [0.75, 0.25]

In [19]:
n_trials = nrows = 10000
n_billboards_passed = ncols = 2

passed = np.random.choice(['ds','wb','wb', 'wb'], size = (n_trials, n_billboards_passed))

In [20]:
passed_df = pd.DataFrame(passed, columns=['B1', 'B2'])
passed_df.head()

B1  B2
0  wb  ds
1  wb  wb
2  wb  wb
3  wb  wb
4  ds  wb

In [21]:
passed_df['Data_science'] = (passed_df['B1'] == 'ds') & (passed_df['B2'] == 'ds')

passed_df.head()

B1  B2  Data_science
0  wb  ds         False
1  wb  wb         False
2  wb  wb         False
3  wb  wb         False
4  ds  wb         False

In [22]:
passed_df.sum()

B1              wbwbwbwbdsdswbwbwbdswbwbwbwbwbwbwbwbwbwbwbwbwb...
B2              dswbwbwbwbwbwbwbdsdswbdswbwbwbdsdswbwbwbwbdswb...
Data_science                                                  608
dtype: object

In [23]:
passed_df['Data_science'].sum()/10000 * 100

6.08

In [24]:
mu = 3
sigma = 1.5


In [25]:
poptarts = np.random.normal(3, 1.5, 5)

poptarts.sum()

13.97391339380923

In [26]:
pop = np.random.normal(3, 1.5, size = (10000, 5))
pop

array([[ 3.79610758,  5.58941489,  3.72683434,  1.80951196,  1.71428793],
       [ 4.44930284,  3.61403569,  1.58571653,  2.21080262,  3.64434626],
       [ 3.410062  ,  4.04348128,  6.62322389,  0.08737874,  4.55048173],
       ...,
       [ 4.23381359,  3.92889581, -0.2361074 ,  2.0350713 ,  2.37549413],
       [ 2.9370665 ,  2.38902903,  3.45125795,  1.44752452, -0.33698129],
       [ 1.47003674,  3.69017579,  2.99519652,  0.76294329,  2.42015548]])

In [27]:
pop.sum(axis = 1) <= 16

array([False,  True, False, ...,  True,  True,  True])

In [28]:
(pop.sum(axis = 1) <= 16).mean()

0.6148

In [29]:
male = np.random.normal(size = 10000, loc = 178, scale = 8)
male

array([175.69210271, 196.62699387, 171.50958005, ..., 168.9571254 ,
       170.12055696, 185.76242379])

In [30]:
female = np.random.normal(size = 10000, loc = 170, scale = 6)
female

array([176.15763806, 175.20157551, 174.75314091, ..., 169.13888136,
       165.88595468, 167.04212711])

In [31]:
(female > male).mean()

0.2138

In [32]:
# 0 = no issues, 1 = issue
install = np.random.choice([0,1], size = (10000, 50), p = [249/250, 1/250])
install


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
fail = 1/250
failed_fif = (np.random.random((10000,50)) > fail).prod(axis = 1).mean()
fail_hun = (np.random.random((10000, 100)) > fail).prod(axis=1).mean()
fail_hunfif = (np.random.random((10000, 150)) > fail).prod(axis=1).mean()
fail_fourfif = (np.random.random((10000, 450)) > fail).prod(axis=1).mean()

In [34]:
failed_fif * 100

81.22

In [35]:
fail_hun * 100

66.77

In [36]:
fail_hunfif * 100

54.52

In [37]:
fail_fourfif * 100

17.01

In [38]:
trucks = np.random.choice([0,1], size = (10000, 3), p = [0.3, 0.7])
trucks

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       ...,
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 1]])

In [39]:
(trucks.sum(axis = 1) == 0).mean()

0.0262

In [40]:
trucks1 = np.random.choice([0,1], size = (10000, 5), p = [0.3, 0.7])
trucks1

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 1],
       ...,
       [0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0]])

In [41]:
(trucks1.sum(axis = 1) >= 1).mean()

0.9973

In [42]:
n_trials = nrows = 7
n_truck = ncols = 1

present = np.random.choice([0, 1], size = (n_trials, n_truck))
present

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0]])

In [46]:
bd = np.random.choice(range(1,366), size = (10000, 23))
bd

array([[185, 345, 205, ..., 125,  92, 213],
       [302,  94, 158, ..., 198, 156, 296],
       [112, 221, 362, ..., 172,  29, 344],
       ...,
       [120, 356, 146, ..., 259,  55, 248],
       [179,  83, 184, ...,  16,  49, 175],
       [183, 167, 314, ..., 144, 283, 193]])

In [47]:
odds_23 = 2/23
odds_20 = 2/20
odds_40 = 2/40

In [48]:
o23 = (np.random.choice((23,2)) > odds_23).prod(axis = 0).mean()
o23

1.0

In [49]:
o20 = (np.random.random((20,2)) > odds_20).prod(axis = 1).mean()
o20

0.75

In [50]:
o40 = (np.random.random((40,2)) > odds_40).prod(axis = 1).mean()
o40

0.875