In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [31]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (10000, 2))

#Here we used the choice function to randomly select an element out of the list of 
#the number 1-6, effectively simulating a dice roll. The second argument supplied to 
#choice is the total number of dice to roll. Once we have generated all the dice rolls, 
#we use the .reshape method to create our matrix with 2 columns and 10,000 rows.
rolls

array([[4, 1],
       [3, 1],
       [6, 5],
       ...,
       [5, 1],
       [2, 4],
       [1, 3]])

In [33]:
roll_doubles = (rolls[:, 0]) == (rolls[:, 1])
roll_doubles

array([False, False, False, ..., False, False, False])

In [34]:
roll_doubles.sum()

1649

In [35]:
roll_doubles.sum()/10000 * 100

16.49

In [36]:
roll1 = np.random.choice([1,2,3,4,5,6], size = (100000, 1))
roll2 = np.random.choice([1,2,3,4,5,6], size = (100000, 1))

In [37]:
(roll1 == roll2).mean()

0.16699

In [42]:
flips = np.random.choice([0,1], size = (100000, 8))
flips

array([[0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 0]])

In [43]:
sums_by_trial = flips.sum(axis=1)
sums_by_trial

array([4, 3, 3, ..., 6, 6, 3])

In [44]:
flips_equal_3 = sums_by_trial ==3
flips_equal_3.sum()

22077

In [45]:
flips_equal_3.sum() / 100000 * 100

22.076999999999998

In [46]:
flips_greater_equal_3 = sums_by_trial > 3
flips_greater_equal_3.sum()

63582

In [47]:
flips_greater_equal_3.sum() / 100000 * 100

63.58200000000001

In [23]:
n_trials = nrows = 100000
n_billboards = ncols = 2

billboards_passed = np.random.choice(['wb', 'wb', 'wb', 'ds'], n_trials * n_billboards).reshape(nrows, ncols)
billboards_passed

array([['wb', 'wb'],
       ['wb', 'wb'],
       ['ds', 'wb'],
       ...,
       ['ds', 'wb'],
       ['ds', 'wb'],
       ['wb', 'wb']], dtype='<U2')

In [24]:
sums_by_trial = billboards_passed.sum(axis=1)
sums_by_trial


TypeError: cannot perform reduce with flexible type

In [20]:
billboards_2 = sums_by_trial == 2
billboards_2.sum()

2083

In [21]:
billboards_2.sum() / 10000 * 100

20.830000000000002